Repository SpiNNakerManchester/spalloc, pull requests merged in 2021-04, with the labels that each got.

#59 Purge Rig from places in the docs where it doesn't belong
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
Labels: blocker, bug

#60 Get nicer version numbers in the documentation
  docs/source/conf.py
  spalloc/job.py
  spalloc/protocol_client.py
Labels: blocker, enhancement, minor

#61 version 1!6.0.1
  requirements.txt
  setup.py
  spalloc/_version.py
Labels: next_release
